[build]
  publish = "dist/public"
  command = "vite build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/public-objects/*"
  to = "https://ruthvikas-bday-surprise-ashmitaj.replit.app/public-objects/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000